import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { ThemeProvider } from "../context/ThemeContext";
import StoreProvider from "../redux/StoreProvider";
import { UserProvider } from "../context/UserContext";
import MainLayout from "../layout/MainLayout";

import ProgressBar from "../components/ProgressBar";
import { MuiToastContainer } from "../utils/toast";

export default async function RootLayout({ children }) {
  let initialNavItems = [];
  let initialFooterItems = [];

  let apiUrl = process.env.NEXT_PUBLIC_API_URL || '';
  if (apiUrl && !apiUrl.startsWith('http://') && !apiUrl.startsWith('https://')) {
    apiUrl = `https://${apiUrl}`;
  }

  try {
    const navRes = await fetch(`${apiUrl}/api/manage-nav-items/get-for-navbar`, { next: { revalidate: 60 } });
    if (navRes.ok) {
      const navData = await navRes.json();
      initialNavItems = navData?.data || [];
    }
  } catch (error) {
    console.error("Failed to fetch nav items for SSR", error);
  }

  try {
    const footerRes = await fetch(`${apiUrl}/api/manage-footer-items/get-for-footer`, { next: { revalidate: 60 } });
    if (footerRes.ok) {
      const footerData = await footerRes.json();
      initialFooterItems = footerData?.data || [];
    }
  } catch (error) {
    console.error("Failed to fetch footer items for SSR", error);
  }
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Basic&family=Inter:wght@300;400;500;600;700;800;900&family=Kalam:wght@300;400;700&family=Caveat:wght@400;500;600;700&family=Dancing+Script:wght@400;500;600;700&family=Pacifico&family=Satisfy&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&family=Courier+Prime:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col" style={{ backgroundColor: 'var(--bg-primary)', transition: 'background-color 0.3s ease', fontFamily: 'Roboto, Inter, sans-serif' }}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider>
            <StoreProvider>
              <UserProvider>
                <ProgressBar>
                  <MainLayout initialNavItems={initialNavItems} initialFooterItems={initialFooterItems}>
                    {children}
                  </MainLayout>
                  <MuiToastContainer />
                </ProgressBar>
              </UserProvider>

            </StoreProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
